version: '3.4'

services:
  db:
    restart: always
    container_name: decide_db
    image: postgres:10.15-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    restart: always
    container_name: decide_web
    image: decide_web:latest
    build: .
    command: ash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - static:/app/static
    depends_on:
      - db

volumes:
  static:
    name: decide_static
  db:
    name: decide_db

